#!/usr/bin/env python3
"""Fill the two pieces of metadata that only a human can obtain, then rebuild.

    python tools/set_metadata.py --doi 10.5281/zenodo.1234567 \
        --orcid-liu 0000-0002-1825-0097 --orcid-chen 0000-0001-2345-6789

Both flags are optional and the script is idempotent: run it again with a
corrected value and it overwrites the previous one. It touches four places that
must never disagree with each other:

  paper/main.tex                  Data availability section, ORCID of each author
  submission/data_availability.md the statement uploaded to Editorial Manager
  submission/cover_letter.md      the archive sentence
  README.md                       the archive badge line

After it runs, rebuild and repackage:

    cd paper && pdflatex -interaction=nonstopmode main && bibtex main \
        && pdflatex -interaction=nonstopmode main && pdflatex -interaction=nonstopmode main
    cd .. && python tools/make_submission.py
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/oscarliu2019/order-provenance-audit"
MARK_BEGIN = "% >>> archive DOI (generated by tools/set_metadata.py)"
MARK_END = "% <<< archive DOI"
SWH_BEGIN = "% >>> Software Heritage archive (generated by tools/set_metadata.py)"
SWH_END = "% <<< Software Heritage archive"


def _strip_block(text: str, begin: str = MARK_BEGIN, end: str = MARK_END) -> str:
    return re.sub(
        re.escape(begin) + r".*?" + re.escape(end) + r"\n",
        "",
        text,
        flags=re.S,
    )


def set_swhid(rev: str, snp: str | None = None) -> None:
    """Record the Software Heritage revision that archives this release.

    A DOI needs an account and a human; Software Heritage archives a public
    repository on an anonymous request and pins the exact revision, so the
    manuscript can name a permanent identifier even before the DOI exists.
    """
    rev = rev.strip()
    if not re.fullmatch(r"swh:1:rev:[0-9a-f]{40}", rev):
        raise SystemExit(f"not a Software Heritage revision id: {rev}")
    visit = f", visit \\texttt{{{snp}}}" if snp else ""
    tex = ROOT / "paper/main.tex"
    s = _strip_block(tex.read_text(), SWH_BEGIN, SWH_END)
    anchor = "\\bibliographystyle{elsarticle-num-names}"
    block = (
        f"{SWH_BEGIN}\n"
        "The repository is also archived permanently in Software Heritage: the revision\n"
        f"from which this manuscript was produced is \\texttt{{{rev}}}\n"
        f"(origin \\url{{{REPO_URL}}}{visit}).\n"
        f"{SWH_END}\n\n"
    )
    s = s.replace(anchor, block + anchor, 1)
    tex.write_text(s)

    da = ROOT / "submission/data_availability.md"
    t = da.read_text()
    t = re.sub(r"\n\nThe repository is also archived permanently in Software Heritage[^\n]*\n(?:[^\n]*\n)?", "\n", t)
    t = t.rstrip() + (
        "\n\nThe repository is also archived permanently in Software Heritage: the revision\n"
        f"from which this manuscript was produced is `{rev}`"
        + (f" (visit `{snp}`)" if snp else "")
        + ".\n"
    )
    da.write_text(t)
    print(f"[swhid] {rev}")


def set_doi(doi: str) -> None:
    doi = doi.strip().removeprefix("https://doi.org/").removeprefix("doi:")
    url = f"https://doi.org/{doi}"

    tex = ROOT / "paper/main.tex"
    s = _strip_block(tex.read_text())
    anchor = "\\bibliographystyle{elsarticle-num-names}"
    block = (
        f"{MARK_BEGIN}\n"
        "The exact release from which every number in this manuscript was computed is\n"
        f"archived, with all artefacts, at \\url{{{url}}} (DOI: \\texttt{{{doi}}}); the\n"
        "repository above is its development mirror.\n"
        f"{MARK_END}\n\n"
    )
    s = s.replace(anchor, block + anchor, 1)
    tex.write_text(s)

    da = ROOT / "submission/data_availability.md"
    s = da.read_text()
    s = re.sub(
        r"A permanent, citable archive of this release will be deposited with a DOI\n"
        r"\(Zenodo\) at the time of submission and the DOI added here\.",
        f"The exact release used for this manuscript is archived permanently and citably\nat <{url}> (DOI: `{doi}`).",
        s,
    )
    s = re.sub(
        r"The exact release used for this manuscript is archived permanently and citably\nat <https://doi\.org/[^>]+> \(DOI: `[^`]+`\)\.",
        f"The exact release used for this manuscript is archived permanently and citably\nat <{url}> (DOI: `{doi}`).",
        s,
    )
    da.write_text(s)

    cl = ROOT / "submission/cover_letter.md"
    s = cl.read_text()
    s = re.sub(r"\n\nThe archived release is at <https://doi\.org/[^>]+>\.", "", s)
    s = s.replace(
        f"<{REPO_URL}>.",
        f"<{REPO_URL}>.\n\nThe archived release is at <{url}>.",
        1,
    )
    cl.write_text(s)

    rd = ROOT / "README.md"
    if rd.exists():
        s = rd.read_text()
        s = re.sub(r"^DOI: .*\n", "", s, flags=re.M)
        s = f"DOI: [{doi}]({url})\n" + s
        rd.write_text(s)
    print(f"[doi] {doi}")


def set_orcid(liu: str | None, chen: str | None) -> None:
    tex = ROOT / "paper/main.tex"
    s = tex.read_text()
    for name, orcid in (("Mianhan Liu", liu), ("Chen Chen", chen)):
        if not orcid:
            continue
        orcid = orcid.strip().removeprefix("https://orcid.org/")
        if not re.fullmatch(r"\d{4}-\d{4}-\d{4}-\d{3}[\dX]", orcid):
            raise SystemExit(f"not an ORCID iD: {orcid}")
        pat = re.compile(
            r"\\author\[1\]\{" + re.escape(name) + r"\}(\[orcid=[^\]]*\])?"
        )
        s, k = pat.subn(
            lambda m: "\\author[1]{" + name + "}[orcid=" + orcid + "]", s, count=1
        )
        if not k:
            raise SystemExit(f"author block for {name} not found")
        print(f"[orcid] {name}: {orcid}")
    if "[orcid=" in s:
        # cas-sc suppresses the footnote only while no iD is registered
        s = s.replace("\\AtBeginDocument{\\renewcommand{\\printorcid}{}}\n", "")
        s = re.sub(
            r"% No ORCID is registered for this submission;.*?\n% footnote that cas-sc emits unconditionally on the title page\.\n",
            "",
            s,
            flags=re.S,
        )
    tex.write_text(s)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--doi")
    ap.add_argument("--orcid-liu")
    ap.add_argument("--orcid-chen")
    ap.add_argument("--swhid", help="swh:1:rev:<40 hex>")
    ap.add_argument("--swh-snapshot", help="swh:1:snp:<40 hex>")
    a = ap.parse_args()
    if not any((a.doi, a.orcid_liu, a.orcid_chen, a.swhid)):
        ap.error("nothing to do: pass --doi, --swhid and/or --orcid-*")
    if a.doi:
        set_doi(a.doi)
    if a.swhid:
        set_swhid(a.swhid, a.swh_snapshot)
    set_orcid(a.orcid_liu, a.orcid_chen)
    print("now rebuild: see the docstring of this file")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
