"""Independent re-derivation of every quantitative claim in the manuscript.

The manuscript prints no typed number: each claim expands a macro from
``paper/numbers.tex``, generated by ``tools/paper_assets.py numbers``. This script
is the adversary of that generator. It re-reads the artefacts, recomputes every
macro that ``paper/main.tex`` actually uses with an independently written
expression, and fails if any value disagrees with what the manuscript prints.

It also enforces two structural properties:
  * every ``\\Num...`` macro used in main.tex is defined in numbers.tex, and
  * every macro used in main.tex has an independent check here,
so a new claim cannot be added to the paper without a verification for it.

Exit status is 0 only if all checks pass.

    python tools/verify_paper_numbers.py            # verify
    python tools/verify_paper_numbers.py --verbose  # print every claim
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import REPO_ROOT, GridConfig  # noqa: E402
from src.detect import aot  # noqa: E402
from src.winerr import load_series as _load_series  # noqa: E402


def load_series(win_dir, name, require_order="index", **kw):
    """Legacy-tolerant read: the archived cells predate the provenance contract."""
    return _load_series(win_dir, name, require_order, legacy_ok=True, **kw)

A = 0.05
PAPER = REPO_ROOT / "paper"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def med(x) -> float:
    return float(np.median(np.asarray(x, dtype=float)))


def nanmed(x) -> float:
    """Median over the cells where the statistic is defined.

    The transfer and hold-out Spearman statistics are undefined for cells whose
    split is too short to fit and evaluate on disjoint halves (ILI), and those
    cells are stored as NaN rather than dropped, so that the row count stays
    equal to the number of cells.
    """
    a = np.asarray(x, dtype=float)
    a = a[np.isfinite(a)]
    return float(np.median(a))


def pct(mask) -> float:
    return float(100.0 * np.mean(np.asarray(mask, dtype=float)))


def tost_ci(diff: np.ndarray) -> tuple[float, float]:
    d = np.asarray(diff, dtype=float)
    n = d.size
    se = d.std(ddof=1) / np.sqrt(n)
    t = stats.t.isf(0.025, n - 1)
    return float(d.mean() - t * se), float(d.mean() + t * se)


def one(values) -> float:
    """The single value a column takes on a homogeneous subset, or an error."""
    u = np.unique(np.asarray(values, dtype=float))
    u = u[np.isfinite(u)]
    if u.size != 1:
        raise ValueError(f"expected one distinct value, found {u.tolist()}")
    return float(u[0])


def collected_tests() -> tuple[int, int]:
    """Count node ids in a collect-only run, rather than trusting its summary line."""
    import subprocess

    out = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    ).stdout
    ids = [ln for ln in out.splitlines() if re.match(r"^tests/\S+\.py::", ln)]
    adv = [i for i in ids if i.startswith("tests/test_provenance.py::")]
    return len(ids), len(adv)


def revision_checks(cfg: GridConfig) -> dict[str, object]:
    """Re-derivation of the macros added by the major revision."""
    art = cfg.path("artifacts_dir")
    R = lambda n: pd.read_csv(art / n)  # noqa: E731

    sens = R("aot_sensitivity.csv")
    tail = R("aot_tail.csv")
    obs = R("observed_perm_scan.csv")
    cc = R("cat_conditions.csv")
    ca = R("cat_analytic_check.csv")
    dep = R("t1_difficulty_depaware.csv")
    clus = R("t1_cluster_summary.csv")
    pur = R("t1_purge_audit.csv")
    cov = R("contract_coverage.csv")
    mig = R("backfill_provenance_migration_report.csv")
    summ = json.loads((art / "t1_depaware_summary.json").read_text())

    # flagged = the fraction NOT rejecting "uniformly permuted", i.e. faults seen
    def flagged(kind: str, param: float) -> float:
        g = sens.loc[(sens.kind == kind) & np.isclose(sens.param, param), "reject"]
        return pct(g == 0)

    blk_params = sorted(sens.loc[sens.kind == "block", "param"].unique())
    par_params = sorted(sens.loc[sens.kind == "partial", "param"].unique())
    ntest, nadv = collected_tests()
    di = dep.loc[dep.condition == "index"]
    ind = ca.loc[ca.condition == "independent"]
    arms = int(obs.n_arms_aot.sum())
    nflag = arms - int(obs.n_arms_aot_rejects.sum())
    bucket = pur.loc[(pur.seq_len == 96) & (pur.pred_len == 720)
                     & (pur.labels_holdout_eligible == 1)]

    def cl(cdef: str, stat: str, col: str, scale: float = 1.0) -> float:
        row = clus.loc[(clus.cluster_def == cdef) & (clus.statistic == stat), col]
        return scale * float(row.iloc[0])

    C: dict[str, object] = {
        # ---- A1: AOT sensitivity, flagged direction ---- #
        "NumSensNBlockRows": int((sens.kind == "block").sum()),
        "NumSensNPartialRows": int((sens.kind == "partial").sum()),
        "NumSensFlagBlockMax": max(flagged("block", p) for p in blk_params),
        "NumSensFlagPartialMildMax": max(
            flagged("partial", p) for p in par_params if p <= 0.10
        ),
        "NumSensFlagPartialQuarter": flagged("partial", 0.25),
        "NumSensFlagPartialHalf": flagged("partial", 0.50),
        "NumSensFlagPartialFull": flagged("partial", 1.00),
        # ---- A2: AOT on the observed loader permutations ---- #
        "NumObsPermGroups": int(obs.shape[0]),
        "NumObsPermArms": arms,
        "NumObsAotMissArms": int(obs.n_arms_aot_rejects.sum()),
        "NumObsAotFlagArms": nflag,
        "NumObsAotFlagPct": 100.0 * nflag / arms,
        "NumObsAotMissGroups": int((obs.n_arms_aot_rejects >= 1).sum()),
        "NumObsAotPMin": float(obs.aot_p_min.min()),
        # ---- A3: tail calibration of the normal reference ---- #
        "NumTailRatioSix": float(tail.loc[np.isclose(tail.alpha, 1e-6), "ratio_to_nominal"].max()),
        "NumTailRatioMedianTwo": med(tail.loc[np.isclose(tail.alpha, 1e-2), "ratio_to_nominal"]),
        "NumTailRatioMedianThree": med(tail.loc[np.isclose(tail.alpha, 1e-3), "ratio_to_nominal"]),
        "NumTailRatioMedianFour": med(tail.loc[np.isclose(tail.alpha, 1e-4), "ratio_to_nominal"]),
        "NumTailRatioMedianFive": med(tail.loc[np.isclose(tail.alpha, 1e-5), "ratio_to_nominal"]),
        "NumTailRatioMedianSix": med(tail.loc[np.isclose(tail.alpha, 1e-6), "ratio_to_nominal"]),
        "NumTailRatioAboveOneRows": int((tail.ratio_to_nominal > 1.0).sum()),
        "NumTailRatioAboveOnePct": pct(tail.ratio_to_nominal > 1.0),
        # ---- A4: sharing structure of the observed permutations ---- #
        "NumObsPermPartialShared": int((obs.perm_sharing == "partial_shared").sum()),
        "NumObsPermAllIdentical": int((obs.perm_sharing == "all_identical").sum()),
        "NumObsPermAllDistinct": int((obs.perm_sharing == "all_distinct").sum()),
        "NumObsPermPairs": int(obs.n_pairs.sum()),
        "NumObsPairsIdenticalNone": int((obs.n_pairs_identical == 0).sum()),
        "NumObsPairsIdenticalOne": int((obs.n_pairs_identical == 1).sum()),
        "NumObsPairsIdenticalTwo": int((obs.n_pairs_identical == 2).sum()),
        "NumObsPairsIdenticalThree": int((obs.n_pairs_identical == 3).sum()),
        "NumObsPairsIdenticalSix": int((obs.n_pairs_identical == 6).sum()),
        "NumObsSpearmanMedian": med(obs.spearman_perm_mean),
        "NumObsSpearmanMin": float(obs.spearman_perm_mean.min()),
        "NumObsSpearmanMax": float(obs.spearman_perm_mean.max()),
        "NumObsPermNonIdentityArms": int(obs.n_arms_misordered.sum()),
        "NumObsPermConsistentGroups": int((obs.perm_consistent == 1).sum()),
        "NumObsCatCertGroups": int((obs.cat_certified == 1).sum()),
        "NumObsCatCertPct": pct(obs.cat_certified == 1),
        "NumObsCatRhoMedian": med(obs.cat_rho_bar),
        "NumObsCatCertIntactGroups": int((obs.cat_certified_intact == 1).sum()),
        "NumObsCatCertIntactPct": pct(obs.cat_certified_intact == 1),
        "NumObsCatRhoIntactMedian": med(obs.cat_rho_bar_intact),
        # ---- A5: CAT under controlled sharing ---- #
        "NumCatCondRows": int(cc.shape[0]),
        "NumCatCondGroups": int(cc.groupby("condition").size().min()),
        # ---- A6: corrected analytic null on independent permutations ---- #
        "NumCatAnalyticRows": int((ca.condition == "independent").sum()),
        "NumCatAnalyticPairs": int(one(ind.m_pairs)),
        "NumCatAnalyticErrMax": float(ind.abs_err_corrected.max()),
        "NumCatAnalyticErrMedian": med(ind.abs_err_corrected),
        "NumCatAnalyticNaiveErrMax": float(ind.abs_err_naive.max()),
        "NumCatAnalyticNaiveErrMedian": med(ind.abs_err_naive),
        "NumCatSdRatioCorrectedMedian": med(ind.sd_ratio_corrected),
        "NumCatSdRatioNaiveMedian": med(ind.sd_ratio_naive),
        "NumCatSdRatioNaiveTheory": float(6.0 ** -0.5),
        # ---- A7: dependence-aware association ---- #
        "NumDepCells": int(di.cell_id.nunique()),
        "NumDepRhoMedian": med(di.assoc_rho_fstd),
        "NumDepRhoQOne": float(np.percentile(di.assoc_rho_fstd, 25)),
        "NumDepRhoQThree": float(np.percentile(di.assoc_rho_fstd, 75)),
        "NumDepRhoIqr": float(
            np.percentile(di.assoc_rho_fstd, 75) - np.percentile(di.assoc_rho_fstd, 25)
        ),
        "NumDepRhoMin": float(di.assoc_rho_fstd.min()),
        "NumDepRhoMax": float(di.assoc_rho_fstd.max()),
        "NumDepBlockSigPct": pct(di.assoc_p_block < A),
        "NumDepBootCiExclPct": pct(di.assoc_rho_ci_excludes_zero == 1),
        "NumDepIidSigPct": pct(di.assoc_p_iid_naive < A),
        "NumDepSequences": int(summ["n_sequences_val_plus_test"]),
        "NumDepSampleSets": int(summ["n_distinct_sample_sets"]),
        "NumDepSampleSetsVal": int(summ["n_distinct_sample_sets_val"]),
        "NumDepDatasets": int(dep.dataset.nunique()),
        "NumDepBlockLenMedian": int(med(di.block_len)),
        "NumDepBlockLenCappedCells": int((di.block_len_capped == 1).sum()),
        "NumDepNPerm": int(one(di.n_perm)),
        "NumDepNBoot": int(one(di.n_boot)),
        "NumDepMinHoldoutWindows": int(summ["min_holdout_windows"]),
        # ---- A8: cluster bootstrap ---- #
        "NumDepClusterBoot": int(one(clus.n_boot)),
        "NumDepClusterSampleSets": int(
            one(clus.loc[clus.cluster_def == "sample_set", "n_clusters"])
        ),
        "NumDepClusterDatasets": int(one(clus.loc[clus.cluster_def == "dataset", "n_clusters"])),
        "NumDepDefectMinusControlMedian": cl("sample_set", "defect_minus_control_median", "point"),
        # ---- A9: purge audit ---- #
        "NumPurgeCells": int(pur.shape[0]),
        "NumPurgeLabelsEligible": int((pur.labels_holdout_eligible == 1).sum()),
        "NumPurgeLabelsIneligible": int((pur.labels_holdout_eligible != 1).sum()),
        "NumPurgeDisjointEligible": int((pur.disjoint_holdout_eligible == 1).sum()),
        "NumPurgeDisjointIneligible": int((pur.disjoint_holdout_eligible != 1).sum()),
        "NumPurgeBucketSeqLen": int(one(bucket.seq_len)),
        "NumPurgeBucketPredLen": int(one(bucket.pred_len)),
        "NumPurgeBucketCells": int(bucket.shape[0]),
        "NumPurgeLegacyOrigins": int(one(bucket.legacy_purge_origins)),
        "NumPurgeLegacyGap": int(one(bucket.legacy_min_origin_gap_actual)),
        "NumPurgeLegacySharedTime": int(one(bucket.legacy_shared_timepoints_at_boundary)),
        "NumPurgeLegacySharedTarget": int(one(bucket.legacy_shared_target_points_at_boundary)),
        "NumPurgeLegacyLeakCells": int(
            (pur.legacy_shared_target_points_at_boundary > 0).sum()
        ),
        # ---- A10: contract coverage ---- #
        "NumContractFaults": int(cov.shape[0]),
        "NumContractDetected": int((cov.detected == 1).sum()),
        "NumContractUndetected": int((cov.detected_by_field == "(none)").sum()),
        "NumContractAdversarialTests": nadv,
        "NumContractRepoTests": ntest,
        "NumBackfillDirs": int((mig.status == "ok").sum()),
        "NumBackfillSidecars": int(mig.n_sidecars_planned.sum()),
        "NumBackfillFailures": int((~mig.status.isin(["ok", "skipped"])).sum()),
    }

    for cond, tag in (("intact", "Intact"), ("independent", "Independent"),
                      ("all_shared", "AllShared"), ("shared_k3", "SharedKThree"),
                      ("shared_k2", "SharedKTwo"), ("two_pairs", "TwoPairs")):
        g = cc.loc[cc.condition == cond]
        C[f"NumCatCond{tag}Cert"] = int((g.certified == 1).sum())
        C[f"NumCatCond{tag}Rho"] = med(g.rho_bar)

    for cdef, ctag in (("sample_set", "SampleSet"), ("dataset", "Dataset")):
        for stat, tag, scale in (
            ("index_median_rho", "DepRho", 1.0),
            ("defect_minus_control_median", "DepDefectMinusControl", 1.0),
            ("index_frac_p_iid_lt_05", "DepIidSig", 100.0),
            ("index_frac_p_block_lt_05", "DepBlockSig", 100.0),
            ("index_frac_ci_excludes_zero", "DepBootCiExcl", 100.0),
        ):
            C[f"Num{tag}{ctag}CiLow"] = cl(cdef, stat, "ci_lo", scale)
            C[f"Num{tag}{ctag}CiHigh"] = cl(cdef, stat, "ci_hi", scale)

    for mode, tag in (("labels", "Labels"), ("disjoint", "Disjoint")):
        C[f"NumPurge{tag}Origins"] = int(one(bucket[f"{mode}_purge_origins"]))
        C[f"NumPurge{tag}RequiredGap"] = int(one(bucket[f"{mode}_required_origin_gap"]))
        C[f"NumPurge{tag}Gap"] = int(one(bucket[f"{mode}_min_origin_gap_actual"]))
        C[f"NumPurge{tag}SharedTime"] = int(
            one(bucket[f"{mode}_shared_timepoints_at_boundary"])
        )
        C[f"NumPurge{tag}SharedTarget"] = int(
            one(bucket[f"{mode}_shared_target_points_at_boundary"])
        )
    return C


def build_checks(cfg: GridConfig) -> dict[str, object]:
    """Every value is recomputed here from the CSV artefacts, independently of
    tools/paper_assets.py."""
    art = cfg.path("artifacts_dir")
    R = lambda n: pd.read_csv(art / n)  # noqa: E731

    runs = R("runs.csv")
    seq = R("aot_sequences.csv")
    cal = R("aot_calibration.csv")
    sens = R("aot_sensitivity.csv")
    theory = R("aot_theory.csv")
    tail = R("aot_tail.csv")
    cert = R("certification.csv")
    catb = R("cat_blocks.csv")
    bat = R("battery.csv")
    t1 = R("t1_difficulty.csv")
    t2 = R("t2_selection.csv")
    tax = R("rng_tax.csv")
    lab = R("label_law.csv")
    eqr = R("equivalence_t1_rho.csv").iloc[0]
    eqt = R("equivalence_t1_transfer.csv").iloc[0]
    eqg = R("equivalence_t2_gain.csv").iloc[0]
    eqd_ = R("equivalence_draws.csv").set_index("stat")

    clean = seq.loc[seq.variant == "index_order"]
    dirty = seq.loc[seq.variant == "full_permutation"]
    obs = seq.loc[seq.variant == "observed_loader_order"]
    ci = catb.loc[catb.variant == "index_order"]
    cd = catb.loc[catb.variant == "full_permutation"]
    cp = catb.loc[catb.variant.str.startswith("pair:")]
    bi = bat.loc[bat.variant == "index_order"]
    bd = bat.loc[bat.variant == "full_permutation"]

    def t1c(cond: str) -> pd.DataFrame:
        return t1.loc[t1.condition == cond]

    def t2c(cond: str) -> pd.DataFrame:
        return t2.loc[t2.condition == cond]

    def labc(cond: str) -> pd.DataFrame:
        return lab.loc[lab.condition == cond]

    # order-provenance masking, recomputed from the raw arrays
    mask_rel, mask_multiset, mask_len = [], [], []
    for cid in runs.loc[runs.val_order == "shuffled", "cell_id"]:
        d = cfg.path("winerr_dir") / cid
        try:
            rec = load_series(d, "val_loader_order", require_order="loader")
            ix = load_series(d, "val_index_order", require_order="index")
        except FileNotFoundError:
            continue
        mask_rel.append(abs(float(rec.mean()) - float(ix.mean())) / abs(float(ix.mean())))
        mask_multiset.append(np.array_equal(np.sort(rec), np.sort(ix)))
        mask_len.append(rec.size == ix.size)

    # the smallest stride at which retained windows no longer overlap
    bdisj = bi.loc[bi.overlap_ratio <= 0.0]
    disj_stride = int(bdisj.stride.min())
    bone = bi.loc[bi.stride == 1]

    blk = sens.loc[sens.kind == "block"]
    par = sens.loc[sens.kind == "partial"]
    blk_max = int(blk.param.max())
    par_min = float(par.param.min())

    def certrow(alpha: float, col: str) -> float:
        return float(cert.loc[np.isclose(cert.alpha, alpha), col].iloc[0])

    C: dict[str, object] = {
        # ---- scale ---- #
        "NumRuns": int(runs.cell_id.nunique()),
        "NumDatasets": int(len(set(runs.dataset))),
        "NumBackbones": int(len(set(runs.backbone))),
        "NumArms": int(len(set(runs.plugin))),
        "NumGpuHours": float(runs.train_seconds.astype(float).sum() / 3600.0),
        "NumTrainedEpochs": int(runs.epochs_run.astype(int).sum()),
        "NumSequences": int(len(clean)),
        "NumWindowsAudited": int(clean.n.astype(int).sum()),
        "NumSampleSets": int(len(clean.drop_duplicates(subset=["dataset", "pred_len", "split"]))),
        "NumDistinctWindows": int(
            clean.drop_duplicates(subset=["dataset", "pred_len", "split"]).n.astype(int).sum()
        ),
        "NumWindowsMin": int(clean.n.min()),
        "NumWindowsMax": int(clean.n.max()),
        # ---- masking ---- #
        "NumMaskChecked": int(len(mask_rel)),
        "NumMaskMaxRelMeanDiff": float(max(mask_rel)) if mask_rel else float("nan"),
        "NumMaskMultisetPct": pct(mask_multiset),
        "NumMaskLengthPct": pct(mask_len),
        # ---- AOT ---- #
        "NumRMedianClean": med(clean.r),
        "NumRMinClean": float(clean.r.min()),
        "NumRMedianCorrupt": med(dirty.r),
        "NumRMaxCorrupt": float(dirty.r.max()),
        "NumZMedianClean": med(clean.z),
        "NumZMinClean": float(clean.z.min()),
        "NumZMinCleanN": int(clean.loc[clean.z.idxmin(), "n"]),
        "NumZMinCleanLong": float(clean.loc[clean.n >= 500, "z"].min()),
        # ---- tail calibration ---- #
        "NumTailSeq": int(tail.cell_id.nunique()),
        "NumTailPerm": int(tail.n_perm.iloc[0]),
        "NumTailNullDraws": int(tail.n_perm.iloc[0] * tail.cell_id.nunique()),
        "NumTailKurtMax": float(tail["kurtosis"].max()),
        "NumTailMaxZ": float(tail.max_z_observed.max()),
        "NumTailRatioTwo": float(tail.loc[np.isclose(tail.alpha, 1e-2), "ratio_to_nominal"].max()),
        "NumTailRatioThree": float(tail.loc[np.isclose(tail.alpha, 1e-3), "ratio_to_nominal"].max()),
        "NumTailRatioFour": float(tail.loc[np.isclose(tail.alpha, 1e-4), "ratio_to_nominal"].max()),
        "NumTailRatioFive": float(tail.loc[np.isclose(tail.alpha, 1e-5), "ratio_to_nominal"].max()),
        "NumTailShortN": int(tail.n.min()),
        "NumTailShortMaxZ": float(tail.loc[tail.n == tail.n.min(), "max_z_observed"].max()),
        "NumZMaxCorrupt": float(dirty.z.max()),
        "NumCleanCertPct": pct(clean.p < A),
        "NumCorruptCertPct": pct(dirty.p < A),
        "NumObservedSeq": int(len(obs)),
        "NumObservedRMedian": med(obs.r),
        "NumObservedCertPct": pct(obs.p < A),
        "NumCleanCertAlphaSix": certrow(1e-6, "clean_certified_pct"),
        "NumCorruptCertAlphaSix": certrow(1e-6, "corrupted_certified_pct"),
        "NumCleanCertAlphaTwelve": certrow(1e-12, "clean_certified_pct"),
        "NumCorruptCertAlphaTwelve": certrow(1e-12, "corrupted_certified_pct"),
        "NumCertTwelveMissSeq": int((clean.p >= 1e-12).sum()),
        "NumCertTwelveMissMaxN": int(clean.loc[clean.p >= 1e-12, "n"].max())
        if int((clean.p >= 1e-12).sum())
        else 0,
        "NumCalibSeq": int(len(cal)),
        "NumCalibMaxAbsDiff": float(np.abs(cal.p_normal - cal.p_perm).max()),
        "NumCalibFprNormal": pct(cal.p_normal < A),
        "NumCalibFprPerm": pct(cal.p_perm < A),
        "NumSensSeq": int(sens.cell_id.nunique()),
        "NumSensBlockMax": blk_max,
        "NumSensBlockMaxRate": pct(blk.loc[blk.param == blk_max, "reject"]),
        "NumSensPartialMin": 100.0 * par_min,
        "NumSensPartialMinRate": pct(par.loc[par.param == par_min, "reject"]),
        "NumSensPartialFullRate": pct(par.loc[np.isclose(par.param, 1.0), "reject"]),
        "NumEqDraws": int(eqd_["draws"].iloc[0]),
        "NumEqDrawRhoSinglePMax": float(eqd_.loc["assoc_rho_fstd", "single_p_max"]),
        "NumEqDrawRhoSinglePMedian": float(eqd_.loc["assoc_rho_fstd", "single_p_median"]),
        "NumEqDrawRhoCertPct": 100.0 * float(eqd_.loc["assoc_rho_fstd", "single_certify_frac"]),
        "NumEqDrawRhoAbsDiffMax": float(eqd_.loc["assoc_rho_fstd", "single_absdiff_max"]),
        "NumEqDrawRhoMeanDiff": float(eqd_.loc["assoc_rho_fstd", "mean_diff"]),
        "NumEqDrawRhoCiLow": float(eqd_.loc["assoc_rho_fstd", "mean_ci95_low"]),
        "NumEqDrawRhoCiHigh": float(eqd_.loc["assoc_rho_fstd", "mean_ci95_high"]),
        "NumEqDrawRhoP": float(eqd_.loc["assoc_rho_fstd", "mean_p_tost"]),
        "NumEqDrawTransferSinglePMax": float(eqd_.loc["spearman_test", "single_p_max"]),
        "NumEqDrawTransferSinglePMedian": float(eqd_.loc["spearman_test", "single_p_median"]),
        "NumEqDrawTransferCertPct": 100.0 * float(eqd_.loc["spearman_test", "single_certify_frac"]),
        "NumEqDrawTransferAbsDiffMax": float(eqd_.loc["spearman_test", "single_absdiff_max"]),
        "NumEqDrawTransferMeanDiff": float(eqd_.loc["spearman_test", "mean_diff"]),
        "NumEqDrawTransferCiLow": float(eqd_.loc["spearman_test", "mean_ci95_low"]),
        "NumEqDrawTransferCiHigh": float(eqd_.loc["spearman_test", "mean_ci95_high"]),
        "NumEqDrawTransferP": float(eqd_.loc["spearman_test", "mean_p_tost"]),
        "NumTaskOneTostClusters": int(eqr["clustered_n_clusters"]),
        "NumTaskOneTostClusterCiLow": float(eqr["clustered_ci95_low"]),
        "NumTaskOneTostClusterCiHigh": float(eqr["clustered_ci95_high"]),
        "NumTaskOneTostClusterP": float(eqr["clustered_p_tost"]),
        "NumTaskOneTransferTostClusterCiLow": float(eqt["clustered_ci95_low"]),
        "NumTaskOneTransferTostClusterCiHigh": float(eqt["clustered_ci95_high"]),
        "NumTaskOneTransferTostClusterP": float(eqt["clustered_p_tost"]),
        "NumTaskTwoTostClusterCiLow": float(eqg["clustered_ci95_low"]),
        "NumTaskTwoTostClusterCiHigh": float(eqg["clustered_ci95_high"]),
        "NumTaskTwoTostClusterP": float(eqg["clustered_p_tost"]),
        "NumRhoMinNHundred": float(theory.loc[theory.n == 100, "rho_min_detectable"].iloc[0]),
        "NumRhoMinNThousand": float(theory.loc[theory.n == 1000, "rho_min_detectable"].iloc[0]),
        # ---- CAT ---- #
        "NumCatBlocks": int(len(ci)),
        "NumCatRhoMedianClean": med(ci.rho_bar),
        "NumCatRhoMinClean": float(ci.rho_bar.min()),
        "NumCatRhoMedianCorrupt": med(cd.rho_bar),
        "NumCatCertCleanPct": pct(ci.p < A),
        "NumCatCertCorruptPct": pct(cd.p < A),
        "NumCatPairs": int(len(cp)),
        "NumCatPairRhoMedian": med(cp.rho_bar),
        "NumCatMissGroups": int((ci.p >= A).sum()),
        "NumCatMissMaxN": int(ci.loc[ci.p >= A, "n"].max()) if int((ci.p >= A).sum()) else 0,
        "NumCatMinN": int(ci.n.min()),
        # ---- battery ---- #
        "NumBatAotStrideOne": 100.0 * float(bone.aot_certify_rate.mean()),
        "NumBatCatStrideOne": 100.0 * float(bone.cat_certify.mean()),
        "NumBatStrideDisjoint": disj_stride,
        "NumBatDisjointRows": int(len(bdisj)),
        "NumBatNDisjoint": int(round(float(bdisj.n.mean()))),
        "NumBatAotDisjoint": 100.0 * float(bdisj.aot_certify_rate.mean()),
        "NumBatCatDisjoint": 100.0 * float(bdisj.cat_certify.mean()),
        "NumBatCorruptAotMax": 100.0 * float(bd.aot_certify_rate.max()),
        "NumBatCorruptCatMax": 100.0 * float(bd.cat_certify.max()),
        "NumBatCorruptAotPct": 100.0 * float(bd.aot_certify_rate.mean()),
        "NumBatCorruptCatPct": 100.0 * float(bd.cat_certify.mean()),
        "NumBatGroups": int(len(bone)),
        "NumBatRows": int(len(bat)),
        # ---- T1 ---- #
        "NumTaskOneCells": int(t1.cell_id.nunique()),
        "NumTaskOneRhoIndexMedian": med(t1c("index").assoc_rho_fstd),
        "NumTaskOneRhoIndexMean": float(t1c("index").assoc_rho_fstd.mean()),
        "NumTaskOneRhoDefectMedian": med(t1c("defect").assoc_rho_fstd),
        "NumTaskOneRhoBestIndexMedian": med(t1c("index").assoc_rho_best.abs()),
        "NumTaskOneRhoBestDefectMedian": med(t1c("defect").assoc_rho_best.abs()),
        "NumTaskOneDecileIndexMedian": med(t1c("index").decile_ratio_fstd),
        "NumTaskOneDecileDefectMedian": med(t1c("defect").decile_ratio_fstd),
        "NumTaskOneSigIndexPct": pct(t1c("index").assoc_p_fstd < A),
        "NumTaskOneSigDefectPct": pct(t1c("defect").assoc_p_fstd < A),
        "NumTaskOneTransferIndexMedian": nanmed(t1c("index").spearman_test),
        "NumTaskOneTransferDefectMedian": nanmed(t1c("defect").spearman_test),
        "NumTaskOneHoldoutIndexMedian": nanmed(t1c("index").spearman_holdout),
        "NumTaskOneHoldoutDefectMedian": nanmed(t1c("defect").spearman_holdout),
        "NumTaskOneTostMargin": float(eqr.margin),
        "NumTaskOneTostMeanDiff": float(eqr.mean_diff),
        "NumTaskOneTostCiLow": float(eqr.ci95_low),
        "NumTaskOneTostCiHigh": float(eqr.ci95_high),
        "NumTaskOneTostP": float(eqr.p_tost),
        "NumTaskOneTransferTostMargin": float(eqt.margin),
        "NumTaskOneTransferTostCiLow": float(eqt.ci95_low),
        "NumTaskOneTransferTostCiHigh": float(eqt.ci95_high),
        "NumTaskOneTransferTostN": int(eqt.n),
        "NumTaskOneTransferTostMeanDiff": float(eqt.mean_diff),
        "NumTaskOneTransferTostP": float(eqt.p_tost),
        # ---- T2 ---- #
        "NumTaskTwoBlocks": int(len(t2c("index"))),
        "NumTaskTwoGainIndexMedian": med(t2c("index").rel_gain_vs_best_fixed),
        "NumTaskTwoGainDefectMedian": med(t2c("defect").rel_gain_vs_best_fixed),
        "NumTaskTwoGainControlMedian": med(t2c("control").rel_gain_vs_best_fixed),
        "NumTaskTwoGainIndexPosPct": pct(t2c("index").rel_gain_vs_best_fixed > 0),
        "NumTaskTwoOracleHeadroomMedian": med(t2c("index").oracle_headroom_pct),
        "NumTaskTwoSignTestP": float(stats.wilcoxon(t2c("index").rel_gain_vs_best_fixed).pvalue),
        "NumTaskTwoTostCiLow": float(eqg.ci95_low),
        "NumTaskTwoTostCiHigh": float(eqg.ci95_high),
        "NumTaskTwoTostMargin": float(eqg.margin),
        "NumTaskTwoTostMeanDiff": float(eqg.mean_diff),
        "NumTaskTwoRandomPenaltyMedian": med(
            100.0
            * (t2c("index").random_arm_mse - t2c("index").best_fixed_mse)
            / t2c("index").best_fixed_mse
        ),
        # ---- label law ---- #
        "NumLabelBlocks": int(len(lab.loc[lab.condition == "index"])),
        "NumLabelEntropyMax": float(np.log2(int(lab.n_arms.max()))),
        "NumLabelModalIndexPct": 100.0 * float(labc("index").modal_share.mean()),
        "NumLabelModalDefectPct": 100.0 * float(labc("defect").modal_share.mean()),
        "NumLabelBestFixedShareIndexPct": 100.0 * float(labc("index").best_fixed_share.mean()),
        "NumLabelBestFixedShareDefectPct": 100.0 * float(labc("defect").best_fixed_share.mean()),
        "NumLabelEntropyIndex": float(labc("index").entropy_bits.mean()),
        "NumLabelEntropyDefect": float(labc("defect").entropy_bits.mean()),
        # ---- repair cost ---- #
        "NumTaxPairs": int(len(tax)),
        "NumTaxMedianAbs": med(tax.abs_rel_diff_pct),
        "NumTaxPNinetyAbs": float(np.percentile(tax.abs_rel_diff_pct, 90)),
        "NumTaxMaxAbs": float(tax.abs_rel_diff_pct.max()),
        "NumTaxSameEpochPct": pct(tax.same_best_epoch),
        "NumTaxSameEpochMedian": med(tax.loc[tax.same_best_epoch == 1, "abs_rel_diff_pct"]),
        "NumTaxDiffEpochMedian": med(tax.loc[tax.same_best_epoch == 0, "abs_rel_diff_pct"]),
        "NumTaxDiffEpochPairs": int((tax.same_best_epoch == 0).sum()),
        "NumTaxOverTenthPct": pct(tax.abs_rel_diff_pct > 0.1),
        "NumTaxIdenticalPct": pct(tax.abs_rel_diff_pct < 1e-9),
        "NumTaxWilcoxP": float(stats.wilcoxon(tax.mse_shuffled, tax.mse_deterministic).pvalue),
    }

    # cross-check the equivalence artefacts against the raw paired data: the
    # intervals in equivalence_*.csv must be reproducible from the per-cell tables.
    def paired(df: pd.DataFrame, value: str, key: str = "cell_id") -> np.ndarray:
        d = df.copy()
        d["_blk"] = d[key] + "_" + d.seed.astype(str) + "_" + d.val_order
        p = d.pivot_table(index="_blk", columns="condition", values=value)
        return (p["defect"] - p["control"]).dropna().to_numpy()

    xc: dict[str, tuple[float, float, float]] = {}
    for tag, arr in (
        ("t1", paired(t1, "assoc_rho_fstd")),
        ("t1transfer", paired(t1, "spearman_test")),
        ("t2", paired(t2, "rel_gain_vs_best_fixed", key="block_id")),
    ):
        lo, hi = tost_ci(arr)
        xc[tag] = (lo, hi, float(arr.mean()))
    C["_xcheck"] = xc
    C.update(revision_checks(cfg))
    return C


def decimals(v: float) -> int:
    s = f"{v!r}"
    if "e" in s or "E" in s:
        return 12
    return len(s.split(".")[1]) if "." in s else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=None)
    ap.add_argument("--verbose", action="store_true")
    a = ap.parse_args(argv)

    cfg = GridConfig(a.config)
    printed = json.loads((PAPER / "numbers.json").read_text())
    tex = (PAPER / "numbers.tex").read_text()
    body = (PAPER / "main.tex").read_text()

    defined = set(re.findall(r"\\newcommand\{\\(Num[A-Za-z]+)\}", tex))
    used = set(re.findall(r"\\(Num[A-Za-z]+)", body))
    checks = build_checks(cfg)
    xcheck = checks.pop("_xcheck")

    problems: list[str] = []
    for m in sorted(used - defined):
        problems.append(f"{m}: used in main.tex but not defined in numbers.tex")
    for m in sorted(used - set(checks)):
        problems.append(f"{m}: used in main.tex but has no independent check")
    for m in sorted(defined - set(printed)):
        problems.append(f"{m}: in numbers.tex but not in numbers.json")

    n_ok = 0
    for m, expected in sorted(checks.items()):
        if m not in printed:
            problems.append(f"{m}: recomputed but absent from numbers.json")
            continue
        got = printed[m]
        if isinstance(expected, int) and not isinstance(expected, bool):
            ok = int(got) == int(expected)
            tol = 0
        else:
            e, g = float(expected), float(got)
            tol = max(1e-9, 0.51 * 10.0 ** (-decimals(g)), 1e-3 * abs(g))
            ok = abs(e - g) <= tol
        if ok:
            n_ok += 1
            if a.verbose:
                print(f"  ok   {m:34s} paper={got!s:>14s}  recomputed={expected}")
        else:
            problems.append(f"{m}: paper prints {got!r}, recomputed {expected!r} (tol {tol:.3g})")

    for tag, prefix in (
        ("t1", "NumTaskOneTost"),
        ("t1transfer", "NumTaskOneTransferTost"),
        ("t2", "NumTaskTwoTost"),
    ):
        lo, hi, mean_diff = xcheck[tag]
        p_lo, p_hi = float(printed[prefix + "CiLow"]), float(printed[prefix + "CiHigh"])
        tol = max(5e-4, 2e-3 * max(abs(p_lo), abs(p_hi)))
        if abs(lo - p_lo) > tol or abs(hi - p_hi) > tol:
            problems.append(
                f"{prefix}Ci*: the paired interval recomputed from the per-cell table "
                f"is [{lo:.5f}, {hi:.5f}], the equivalence artefact says "
                f"[{p_lo}, {p_hi}]"
            )
        key = prefix + "MeanDiff"
        if key in printed and abs(mean_diff - float(printed[key])) > tol:
            problems.append(
                f"{key}: recomputed paired mean difference {mean_diff:.5f}, "
                f"artefact says {printed[key]}"
            )

    for rel in ("tables/grid.tex", "tables/certification.tex", "tables/sensitivity.tex",
                "tables/battery.tex", "tables/downstream_t1.tex", "tables/downstream_t2.tex",
                "tables/rng_tax.tex", "tables/observed_perm.tex", "tables/cat_conditions.tex",
                "tables/cat_analytic.tex", "tables/depaware.tex", "tables/purge_audit.tex",
                "tables/contract_coverage.tex", "figs/sequence.pdf", "figs/separation.pdf",
                "figs/battery.pdf", "figs/downstream.pdf", "figs/rngtax.pdf"):
        if not (PAPER / rel).exists():
            problems.append(f"missing generated asset: paper/{rel}")

    unused = sorted(defined - used)
    print(
        f"\n{n_ok}/{len(checks)} claims re-derived from artefacts; "
        f"{len(used)} macros used in main.tex; {len(unused)} defined but unused."
    )
    # an unused macro is a warning, not an error: a claim may be written up later
    if unused:
        print(f"WARNING: {len(unused)} macro(s) defined and verified but not yet cited in main.tex")
    if unused and a.verbose:
        print("  unused:", ", ".join(unused))
    if problems:
        print(f"\nFAILED with {len(problems)} problem(s):")
        for p in problems:
            print("  -", p)
        return 1
    print("all claims verified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
